### ISSUE TITLE
Definir Lista de User Stories com Testes de Aceitação

### ISSUE THREAD

**Issue by tacianosilva** [Sergiany/kungfood#1]
O gerente deve colocar pelo menos dois requisitos por membro da equipe. Cada membro da equipe vai elaborar o user story e seus testes de aceitação.

**Comment by tacianosilva** [comment]
@Sergiany as tarefas para a equipe deve ser cadastrada com o label documentação.

**Comment by acarolsf** [comment]
https://docs.google.com/document/d/1rjs7m0d3NAph8gKJotUZ52IGrkvG1wRfhvl2UGJuy_c/edit?usp=sharing
