### ISSUE TITLE
Criar página Wiki com os papéis da equipe e a matriz de competência

### ISSUE THREAD

**Issue by tacianosilva** [Sergiany/kungfood#5]
Criar página Wiki com tabelas com os papéis da equipe e a matriz de competência. Criei um milestone de definição apenas para colocar o resumo da equipe.

**Comment by Sergiany** [comment]
![image](https://user-images.githubusercontent.com/23044094/31249228-ef7717b6-a9ec-11e7-84cc-369e894f804d.png)

**Comment by tacianosilva** [comment]
@Sergiany se uma atividade for finalizada ela deve ser fechada!
