### ISSUE TITLE
Criar página Wiki com o resumo do documento de visão

### ISSUE THREAD

**Issue by tacianosilva** [Sergiany/kungfood#6]
Criar página wiki com o resumo do documento de visão. Ou seja, deve conter um pequena descrição e a lista de requisitos do sistema.

**Comment by Sergiany** [comment]
## **Descrição do Projeto**

O projeto Kung Food é um sistema de cadastro para uma empresa de Fast Food. Onde nesse sistema será cadastrado produtos e seus valores para o cliente da empresa realizar a consulta e assim realizar o seu pedido o qual será cadastrado no sistema. Com isso, o dono da empresa vai ter acesso aos pedidos dos clientes para agilizar na preparação do produto final.

## **Requisitos Funcionais**

RF01 - o sistema deve possibilitar o cliente fazer o pedido via web.
RF02 - o sistema deve possibilitar o dono consultar todos os pedidos de qualquer dia.
RF03 - o sistema deve possibilitar os funcionários a visualizar os pedidos.
RF04 - o sistema deve possibilitar o cliente a cancelar o pedido.
RF05 - o sistema deve abrir uma tela de login para os funcionários.
RF06 - o cliente deve estar cadastrado para fazer o pedido.
RF07 - o sistema deve permitir a busca de produtos a alterar dos produtos.
RF08 - o sistema deve permitir que somente UM funcionário altere algo sobre os produtos.
RF09 - o sistema deve permitir o cadastro, exclusão, edição e busca do produto.
RF10 - o sistema deve permitir o cadastro, exclusão, edição e busca do cliente.
RF11 - o sistema deve permitir o cadastro, exclusão, edição e busca do funcionário.

**Comment by tacianosilva** [comment]
@Sergiany se uma atividade for finalizada ela deve ser fechada!
