### ISSUE TITLE
Criar arquitetura com o Dicionário de dados

### ISSUE THREAD

**Issue by acarolsf** [Sergiany/kungfood#7]

**Comment by Sergiany** [comment]
![arquitetura](https://user-images.githubusercontent.com/23044094/31300003-bc0565a0-aac7-11e7-906e-fb87f267d3eb.png)

**Comment by Sergiany** [comment]
![arquitetura](https://user-images.githubusercontent.com/23044094/33488712-484f61b6-d690-11e7-9f0e-5598638fd57e.png)
