### ISSUE TITLE
Criar Modelo Conceitual (Diagrama de Classes UML)

### ISSUE THREAD

**Issue by Sergiany** [Sergiany/kungfood#8]

**Comment by Sergiany** [comment]
![uml](https://user-images.githubusercontent.com/23044094/31309586-ca8cd0e4-ab5e-11e7-8b05-68ae087d9ac1.jpg)

**Comment by tacianosilva** [comment]
@Sergiany, @acarolsf e @mikmichel: lembre-se que ao criar uma issue (tarefa) deve-se informar para qual membro ela é, e qual milestone e projeto ela pertence.
